-- =============================================================
-- IMS schema for Supabase local
-- Centres / items / stock / SCI forms + auth + RLS + storage
-- =============================================================

create extension if not exists pgcrypto;

-- -------------------------------------------------------------
-- Centres (org hierarchy)
-- -------------------------------------------------------------
create table if not exists public.centres (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('CENTRE','SUB CENTRE','POINT','ASO ADMIN')),
  "parentId" bigint references public.centres(id) on delete set null
);

-- -------------------------------------------------------------
-- Items (stock item master)
-- -------------------------------------------------------------
create table if not exists public.items (
  id bigint generated by default as identity primary key,
  name text unique not null,
  code text default '',
  description text default '',
  category text default ''
);

-- -------------------------------------------------------------
-- Stock register (per centre per item)
-- -------------------------------------------------------------
create table if not exists public.stock_items (
  id bigint generated by default as identity primary key,
  "centreId" bigint not null references public.centres(id) on delete cascade,
  item text not null,
  qty bigint not null default 0,
  unique ("centreId", item)
);

-- -------------------------------------------------------------
-- SCI forms
-- -------------------------------------------------------------
create table if not exists public.sci_forms (
  id bigint generated by default as identity primary key,
  "formType" text not null,
  "formTitle" text default '',
  "centreId" bigint references public.centres(id) on delete set null,
  "centreName" text default '',
  "sewadarName" text not null default '',
  "sewadarBadge" text default '',
  details jsonb default '{}'::jsonb,
  remarks text default '',
  quantity bigint,
  amount numeric(14,2),
  "destinationCentreId" bigint references public.centres(id) on delete set null,
  "destinationCentreName" text default '',
  document text default '',
  "documentName" text default '',
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  "submittedAt" timestamptz not null default now(),
  "submittedBy" uuid references auth.users(id) on delete set null
);

-- -------------------------------------------------------------
-- Profiles (link to auth.users)
-- -------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  name text not null,
  role text not null check (role in ('SUPERADMIN','ASO_VIEWER','CENTRE')),
  "userType" text not null default '',
  "centreId" bigint references public.centres(id) on delete set null,
  "centreName" text default ''
);

-- -------------------------------------------------------------
-- Public helper: is current user a SUPERADMIN?
-- -------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'SUPERADMIN'
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

-- -------------------------------------------------------------
-- Public read-only view used on the login page (reset password dropdown)
-- -------------------------------------------------------------
create or replace view public.org_users as
select p.id as "authId", p.username, p.name, coalesce(nullif(p."userType", ''), p.role) as type
from public.profiles p;

grant select on public.org_users to anon, authenticated;

-- -------------------------------------------------------------
-- RLS
-- -------------------------------------------------------------
alter table public.centres enable row level security;
alter table public.items enable row level security;
alter table public.stock_items enable row level security;
alter table public.sci_forms enable row level security;
alter table public.profiles enable row level security;

-- centres: everyone logged-in reads; only admin writes
create policy "centres_select" on public.centres for select to authenticated using (true);
create policy "centres_admin_insert" on public.centres for insert to authenticated with check (public.is_admin());
create policy "centres_admin_update" on public.centres for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "centres_admin_delete" on public.centres for delete to authenticated using (public.is_admin());

-- items: everyone logged-in reads; only admin writes
create policy "items_select" on public.items for select to authenticated using (true);
create policy "items_admin_insert" on public.items for insert to authenticated with check (public.is_admin());
create policy "items_admin_update" on public.items for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "items_admin_delete" on public.items for delete to authenticated using (public.is_admin());

-- stock_items: everyone reads; only admin writes
create policy "stock_select" on public.stock_items for select to authenticated using (true);
create policy "stock_admin_insert" on public.stock_items for insert to authenticated with check (public.is_admin());
create policy "stock_admin_update" on public.stock_items for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "stock_admin_delete" on public.stock_items for delete to authenticated using (public.is_admin());

-- sci_forms: everyone logged-in reads; anyone can insert; only admin changes status
create policy "sci_select" on public.sci_forms for select to authenticated using (true);
create policy "sci_insert" on public.sci_forms for insert to authenticated with check (auth.uid() is not null);
create policy "sci_admin_update" on public.sci_forms for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- profiles: users read only their own row via RLS; is_admin() bypasses using security definer
create policy "profiles_select_own" on public.profiles for select to authenticated using (id = auth.uid());
create policy "profiles_admin_select" on public.profiles for select to service_role using (true);

-- -------------------------------------------------------------
-- Storage bucket for PDF uploads (public)
-- -------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', true)
on conflict (id) do nothing;

create policy "uploads_read" on storage.objects for select using (bucket_id = 'uploads');
create policy "uploads_write" on storage.objects for insert to authenticated with check (bucket_id = 'uploads');

-- -------------------------------------------------------------
-- Seed: centre hierarchy (from Django seed_centres.py)
-- -------------------------------------------------------------
insert into public.centres (id, name, type, "parentId") values
  (1,  'ANKHEER',          'CENTRE', null),
  (2,  'BALLABGARH',       'CENTRE', null),
  (3,  'DLF CITY GURGAON', 'CENTRE', null),
  (4,  'TAORU',            'CENTRE', null),
  (5,  'FIROZPUR JHIRKA',  'CENTRE', null),
  (6,  'GURGAON',          'CENTRE', null),
  (7,  'MOHANA',           'CENTRE', null),
  (8,  'ZAIBABAD KHERLI',  'CENTRE', null),
  (9,  'NANGLA GUJRAN',    'CENTRE', null),
  (10, 'N.I.T. NO. 2',     'CENTRE', null),
  (11, 'BAROLI',           'CENTRE', null),
  (12, 'HODAL',            'CENTRE', null),
  (13, 'PALWAL',           'CENTRE', null)
on conflict (id) do nothing;

insert into public.centres (id, name, type, "parentId") values
  (14, 'KASAN',                'POINT', 6),
  (15, 'FATEHPUR BILLOCH',     'POINT', 7),
  (16, 'BAHIN',                'POINT', 13),
  (17, 'HASANPUR (FARIDABAD)', 'POINT', 13),
  (18, 'HATHIN',               'POINT', 13),
  (19, 'MANDKOLA',             'POINT', 13),
  (20, 'NAYAGAON',             'POINT', 13),
  (21, 'NUH',                  'POINT', 3),
  (22, 'BADHA SIKENDERPUR',    'POINT', 6),
  (23, 'BILASPUR (FARIDABAD)', 'POINT', 6),
  (24, 'BUDHERA',              'POINT', 6),
  (25, 'DUNDAHERA',            'POINT', 6),
  (26, 'JATAULA',              'POINT', 6)
on conflict (id) do nothing;

-- -------------------------------------------------------------
-- Seed: stock item master
-- -------------------------------------------------------------
insert into public.items (name) values
  ('Prasad'),
  ('Prasad Box'),
  ('Ladoos'),
  ('Books'),
  ('Audio CD'),
  ('Video DVD'),
  ('Stationery'),
  ('Cleaning Material')
on conflict (name) do nothing;

-- -------------------------------------------------------------
-- Seed: a little example stock so the register looks alive
-- -------------------------------------------------------------
insert into public.stock_items ("centreId", item, qty) values
  (1, 'Prasad', 120), (1, 'Prasad Box', 40), (1, 'Ladoos', 200), (1, 'Books', 55),
  (2, 'Prasad', 90),  (2, 'Books', 12),  (2, 'Stationery', 30),
  (6, 'Prasad', 250), (6, 'Ladoos', 180), (6, 'Audio CD', 15), (6, 'Video DVD', 22), (6, 'Books', 140)
on conflict ("centreId", item) do nothing;