-- 0006: Inventory Masters.
--
-- 1) Item codes: the system auto-generates an item code (ITM-###) for every
--    new item the moment it is created. Existing items are back-filled from
--    their id so codes are unique and stable.
-- 2) Document master: a documents registry. Every row is a named document
--    (each SCI form plus a mandatory "GRN" document) with a manually editable
--    document number (used for the GRN no.) and an uploaded PDF attachment.
-- Idempotent so it can be applied to an already-running local stack.

-- -------- auto item codes --------
create sequence if not exists public.items_code_seq start 1;

create or replace function public.items_assign_code()
returns trigger language plpgsql as $$
begin
  if new.code is null or new.code = '' then
    new.code := 'ITM-' || lpad(nextval('public.items_code_seq')::text, 3, '0');
  end if;
  return new;
end $$;

drop trigger if exists items_code_before on public.items;
create trigger items_code_before
  before insert on public.items
  for each row execute function public.items_assign_code();

do $$
begin
  update public.items
     set code = 'ITM-' || lpad(id::text, 3, '0')
   where code is null or code = '';
  perform setval('public.items_code_seq',
                 greatest(coalesce((select max(id) from public.items), 0), 1),
                 true);
end $$;

-- -------- documents registry --------
create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null default '',
  "docNo" text not null default '',
  document text not null default '',
  "documentName" text not null default '',
  "updatedAt" timestamptz not null default now(),
  "updatedBy" uuid references auth.users(id) on delete set null
);

alter table public.documents enable row level security;

drop policy if exists "documents_select_all" on public.documents;
drop policy if exists "documents_insert_all" on public.documents;
drop policy if exists "documents_update_all" on public.documents;
drop policy if exists "documents_delete_admin" on public.documents;

create policy "documents_select_all" on public.documents
  for select to authenticated using (auth.uid() is not null);
create policy "documents_insert_all" on public.documents
  for insert to authenticated with check (auth.uid() is not null);
create policy "documents_update_all" on public.documents
  for update to authenticated using (auth.uid() is not null) with check (auth.uid() is not null);
create policy "documents_delete_admin" on public.documents
  for delete to authenticated using (
    exists (select 1 from public.profiles p
             where p.id = auth.uid() and (p.role = 'SUPERADMIN' or p."userType" = 'ASO ADMIN'))
  );

-- grant table/sequence access (new table, so grants must be repeated here)
grant select, insert, update, delete on table public.documents to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;
grant usage on schema public to anon, authenticated, service_role;

-- seed: a GRN document plus one row per SCI form type
insert into public.documents (name, description) values
  ('GRN', 'Goods Receipt Note'),
  ('SCI45', 'Condemnation of Articles & Requirement of Items / Material Against Condemnation'),
  ('SCI53', 'Requirement of Items / Material from Beas'),
  ('SCI76', 'Material Issue Voucher'),
  ('SCI43', 'Transfer of Surplus Items from One Centre to Another'),
  ('SCI15', 'Offer of Items / Material in Donation'),
  ('SCI34', 'Sale Proceeds of Condemned / Surplus Items / Scrap Etc.')
on conflict (name) do nothing;