-- 0009: Physical Stock Verification Register (ledger).
-- The Stock Register page uses this ledger, matching the paper register format:
-- S.No | Satsang Place | Name of Item | Stock Register Page No. | Approval Number |
-- Approval Date | Qty as per Stock Register (A) | Physically Available (B) |
-- Difference (A-B) | Reason for Difference | Remarks
-- qtyA is snapshotted from stock_items at entry time; qtyB is the physically
-- counted quantity entered during verification; difference is auto-computed.
-- Every verification creates a NEW dated row (history is kept).
create table if not exists public.stock_register (
  id bigint generated by default as identity primary key,
  "centreId" bigint not null references public.centres(id) on delete cascade,
  item text not null,
  "pageNo" text not null default '',
  "approvalNo" text not null default '',
  "approvalDate" date,
  "qtyA" integer not null default 0,
  "qtyB" integer not null default 0,
  "difference" integer generated always as ("qtyA" - "qtyB") stored,
  reason text not null default '',
  remarks text not null default '',
  "verifiedAt" timestamptz not null default now(),
  "verifiedBy" text not null default ''
);

alter table public.stock_register enable row level security;

drop policy if exists "stock_register_select_all" on public.stock_register;
drop policy if exists "stock_register_insert_all" on public.stock_register;
drop policy if exists "stock_register_update_all" on public.stock_register;
drop policy if exists "stock_register_delete_admin" on public.stock_register;

create policy "stock_register_select_all" on public.stock_register
  for select to authenticated using (auth.uid() is not null);
create policy "stock_register_insert_all" on public.stock_register
  for insert to authenticated with check (auth.uid() is not null);
create policy "stock_register_update_all" on public.stock_register
  for update to authenticated using (auth.uid() is not null) with check (auth.uid() is not null);
create policy "stock_register_delete_admin" on public.stock_register
  for delete to authenticated using (
    exists (select 1 from public.profiles p
             where p.id = auth.uid() and (p.role = 'SUPERADMIN' or p."userType" = 'ASO ADMIN'))
  );

grant select, insert, update, delete on table public.stock_register to anon, authenticated, service_role;
grant usage on all sequences in schema public to anon, authenticated, service_role;
grant usage on schema public to anon, authenticated, service_role;

create index if not exists stock_register_centre_idx on public.stock_register ("centreId");
create index if not exists stock_register_item_idx on public.stock_register (item);